\c blogs_dev;

INSERT INTO blogs (title, name, age, content, created_at, is_anonymous) VALUES 
('Cyber Bullying', 'Sarah', 14, 'A few weeks ago I found out 2 of my friends had been taking photos of me and sending them around to others. They also made a photo and video of me as a whale. I felt so alone and lost until I went to the police but the ADA says we can’t charge the girls with anything because this was the first time they did something. But recently they have been doing this to 2 other girls so we aren’t giving up!', 'May 23, 2023', false),
('Boys Will be Boys', 'Anonymous', 11, 'When I was in 6th grade, I was bullies by this guy Tyler (not his real name). Tyler would call me “trash” or “a walking brick” when I was just trying to play basketball. This may not seem like much but I was really insecure about it because he was one of the “popular guys” and since I went to a private school, if I did something stupid in response, everyone would know about it. Then it started getting physical and this guy would purposely run into me, pushing me to the floor. When I told my parents, all they said was “Boys will be boys” and “he just likes you”. Parents, take a step back and look at that. Boys just get a free pass just because they’re boys and immature. I have heard this many many times from many parents, and it hurts dude. Later, he started easing down and bullying my friends instead.', 'May 5, 2023', true),
('School sucks', 'Leslie', 13, 'I have always been on the bigger side but it never really bugged me till 7th grade. I had lost a lot of weight and seem happier and I had stop wearing oversizes hoodies and I was now in Large and medium instead of XL. I was happy but then boy would say stuff about it and so would some of my friends. then it started happening a lot more. then Summer rolled around and i lost more weight but i knew it would never go away because my dad was bigger but when 8th grade started The people I was friends with would make fun of my body and I stop eating I had people telling that i was a cow and needed to go on a run. I let their words get to me. I still have people calling me fat and by now it had gotten worst and i was too scared to tell. Me and this girl used to be friends and one day we just stopped talking and then she started bullying me making fun of me, when she would walk beside me she would make noises at me or she would call me fat for just looking at her. It hurt and i wanted to punch her so bad i was ready too but i couldn’t because i’m still too scared to tell anyone and being away from my school would be a lot better.', 'April 25, 2023', false),
('Racism', 'Anonymous', 16, 'I am 16 and i am from México, i was new to the U.S . I didn’t know much English, I was 10 and was in 5th grade so once I knew that I had to change class, in between those time I was tripped by random people and my books would fall to the ground and so did i. It happened over and over again so I went with the principal at my school and told her what’s happening, the only thing she tells me “what’s wrong with you people” and dismissed me I was angry but at the same sad. I didn’t tell my parents but I was bullied because of my race. there is more I want to say but I will remember this for life.', 'April 26, 2023', true),
('Disabled Bullying', 'Sean', 12, 'Ever since I could remember I would always get looked down upon because of my disability. I knew for a fact it wasn’t my fault but the words that the children spoke of me at school really hurt my heart and destroyed my self-esteem. I spoke with my parents about this and then they reported the issue to the school’s president. The kids stopped saying harmful words to me and I managed to gain my confidence to go back to school and achieve my goal of one day being successful.', 'March 15, 2023', false),
('Bullies', 'Anonymous', 13, 'I remember last year I was 12 and just started at new middle school. I felt alone and had no friends. I tried to sit with lunch with a group of girls I recognized. They always left me out and never listened to me. Everyone I talked to use to make fun of me. I then lost my self-esteem. Then, I acted reckless and lost my parents’ trust. If you are being bullied, stay strong. I know it is hard.', 'January 20, 2023', true),
('Tired, weary and confused', 'Anonymous', 15, 'For months now at my school I’ve been bullied by this group of girls, or as me and my friend who we’ll call Blondie like to refer to them as, the bully buddies. They’ve been attacking me and Blondie and my other friend who we’ll call Blue Eyes, for months. The attacks range from physical violence to verbal threats to fake accusations. One day the leader, who we’ll call Snotface, threw all kinds of homophobic, racist, inappropriate, disrespectful comments at me and Blue Eyes. We reported Snotface and lo and behold, a teacher actually did something about it! Snotface and her friend (alias Two-Sided) spent the rest of the day in our vice principal’s office being questioned. Snotface’s parents and my parents were called in and Snotface was given a month of detention. The principal is also putting in measures to protect me Blondie and Blue Eyes from Snotface and Two-Sided. The moral of this story is: If you report someone once and nothing happens, KEEP TRYING. Tell as many people with as much description as you can, till the bullies get what’s coming to them. I know it’s cliche, but it’s true. And remember: you are smart, strong, beautiful, and loved. And don’t let anyone change that.', 'May 25, 2023', true),
('Hell on Earth and bullying', 'Xiomara', 12, 'Hitting and hurting me so bad my heart was broken into 10 little million pieces, and I have lost my faith in people and the world too', 'May 9, 2023', false),
('Its hard to be yourself', 'Jay', 14, 'It all started in 5th grade because this was when I transferred schools. So I’ve always been an extroverted kid, and in 5th grade, I went to what I’ll just call stonewall intermediate. This school was known to be the best school district in my state but the problem was it had tons of spoiled kids. I was a good kid but would get in trouble a lot and got lunch detention and Friday night school often. but I never meant anything but they did ……the boys. but these boys bullied me for having a Samsung, being chubby, having acne, and calling me names. The bullies pointed out anything they could point out, and this was especially hard on me because I didn’t have any friends well close ones, and little by little I showed less and less emotion and became very introverted. I wish I had reached out for help sooner because in my freshmen year of high school I made a real friend and she helped me reach out to get them suspended for a few weeks luckily because my school had a strict bullying policy.', 'May 5, 2021', true),
('Bullying in Silence', 'S.', 13, 'hi it’s S. i’ve been bullied most all my life because of my hearing. i’m half deaf in my left ear. i was called names, tripped, this one girl was my friend at the beginning and then she started to be mean to me, like everyday. i did get help but it didn’t seem to stop. but then years later it did. she moved and i don’t see her anymore. but there are these boys that call me names all the time but i moved away and am going to another school and it’s a lot better. just know you’re not alone and never will be but GET HELP IF YOU NEED IT!', 'May 7, 2022', false);

-- reference: https://www.pacerteensagainstbullying.org/